services:
  dev_db:
    image: postgres:16
    environment:
      POSTGRES_USER: sgs
      POSTGRES_PASSWORD: sgs-pass
    ports:
      - 5432:5432
    volumes:
      - dev_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
  test_db:
    image: postgres:16
    environment:
      POSTGRES_USER: sgs
      POSTGRES_PASSWORD: sgs-pass
    ports:
      - 5433:5432
    volumes:
      - test_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  dev_data:
  test_data:
