name: Docs

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v6

      - run: nix build -L .#sgs-docs
      - name: Fix file permissions
        run: cp -r --no-preserve=mode,ownership result/ _site/

      - uses: actions/upload-pages-artifact@v3

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deploy-pages
